name: 'Deploy a service to Wonderland 2'
description: 'Deploy a service to Wonderland 2'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  token:
    description: 'A GitHub token to use with wonderland'
    required: true
  bastion_key:
    description: 'Ssh key for authentication in the bastion host'
    required: true
  workspace:
    required: false
    description: 'The wonderland workspace to deploy your application to (prod/stage)'
    default: 'prod'
  wonderland_manifest:
    required: false
    description: 'The Wonderland 2 manifest file'
    default: 'wonderland2.yaml'
  timeout:
    required: false
    description: 'Maximum time to wait for the deployment to become available'
    default: '10m'
  delete:
    required: false
    description: 'Delete the service instead of deploying it'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.bastion_key }}
    - ${{ inputs.workspace }}
    - ${{ inputs.wonderland_manifest }}
    - ${{ inputs.timeout }}
    - ${{ inputs.delete }}
