name: 'Deploy a service to Wonderland 2'
description: 'Deploy a service to Wonderland 2'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  token:
    description: 'A GitHub token to use with wonderland'
    required: true
    default: ''
  bastion_key:
    description: 'Ssh key for authentication in the bastion host'
    required: true
    default: ''
  workspace:
    description: 'The workspace to deploy your application (prod/stage)'
    required: true
    default: 'stage'
  wonderland_manifest:
    description: 'The Wonderland 2 manifest file'
    required: true
    default: 'wonderland2.yaml'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.bastion_key }}
    - ${{ inputs.workspace }}
    - ${{ inputs.wonderland_manifest }}
